### ISSUE TITLE
"Error setting Dns Entries" when adding more than 1 DNS entry simultaneous

### ISSUE THREAD

**Issue by kevinvalk** [aequitas/terraform-provider-transip#22]
When applying a change into multiple records at the same time, Transip will start throwing errors.

As you mention in the source, it does indeed seem like some locking mechanism.  I added `strings.Contains(err.Error(), "Error setting Dns Entries")` to https://github.com/aequitas/terraform-provider-transip/blob/4ad6bf051ab189a98221847d9fefd52872f1bb81/resource_transip_dns_record.go#L203. It works somewhat, but I often get an "inconsistent result after apply" error.

The same thing happens for updates and deletes. This really makes it impossible to use Terraform with Transip. Do you also have this issue, how do you tackle this? Any other ideas on how to resolve this?

```terraform
locals {
  test_dns = toset([
    "A", "B", "C", "D", "E", "F", "G",
  ])
}

resource "transip_dns_record" "mx" {
  for_each = local.test_dns

  domain  = "test.nl"
  name    = each.value
  type    = "TXT"
  expire  = 300
  content = ["simple test"]
}

```

**Comment by kevinvalk** [comment]
I think we are running into the same thing as https://github.com/terraform-providers/terraform-provider-aws/issues/483.

A solution that "just works" is adding `-parallelism=1`, you get no errors, smooth sailing. BUT, it is **slow**...

In theory we can force serialization by adding mutexes for DNS records, but we should really solve this problem at its core (at Transip side).

**Comment by kevinvalk** [comment]
Response from Transip:

> Vermoedelijk krijg je dit probleem doordat bij het wijzigen van de DNS entries deze 'gelockt' wordt tot het volledig is gesigneerd en afgerond. Dit betekent dus dat het parallel aanpassen van DNS-wijzigingen niet mogelijk is.
> 
> Deze manier van werken is bewust gedaan en zullen ook geen wijzigingen aan onze kant voor komen.

Boils down to:
> Correct, we lock DNS changes, so changing multiple records is not possible. **We will not change this behavior from our side.**

**Comment by aequitas** [comment]
This has been a problem with the old API and I hoped it would go away with the new one but it didn't. That's why I added this note to the readme: https://github.com/aequitas/terraform-provider-transip#notes. So yes, the parallelism workaround is the only way to make it work reliable at the moment.

Thanks for looking into this further and even contacting Transip. Sad they won't do anything about this. Especially since the API doesn't consistently respond when the resource is locked. So from a Terraform perspective the change went without error. But then no actual change is made. While on some other request you might have gotten an error instead. 

I thought about using mutexes as well, but I don't know if it will solve the problem of the slowness and also I don't know how well it will behave with Terraform internals (the parallel resource scheduler). I'll need to do a little more investigation regarding that.

There are already tests for this behaviour in the codebase should you want to give it a try: https://github.com/aequitas/terraform-provider-transip/blob/master/resource_transip_dns_record_test.go#L123-L205

**Comment by kevinvalk** [comment]
Perhaps we can keep tracking this issue here, the solution would probably be the same as described in https://discuss.hashicorp.com/t/whole-provider-process-synchronization/2006/4.

It is also used in AWS https://github.com/terraform-providers/terraform-provider-aws/blob/91fd73606fa7d8dbbe29bffec5010dd9ad341a1b/aws/provider.go#L1066

Terraform has the `MutexKV` mutex that we could use to lock per domain https://github.com/hashicorp/terraform/blob/master/helper/mutexkv/mutexkv.go.

If you want I can try to refactor resource_transip_dns_record.go a bit with `MutexKV` to see performance and errors.
