### ISSUE TITLE
Authentication Issue 

### ISSUE THREAD

**Issue by angelosleebos** [aequitas/terraform-provider-transip#41]
It seems that something has changed at transip in terms of Authentication? Is this correct?  I have already tried to supply the private key base64encoded, but I still get this error message: 

provider "transip" {
  account_name = ""
  private_key  = base64encode(file(""))
}

Error: Failed to get available products: could not get token from authenticator: could not decode private key

Before delivering the private key encoded, I got this error message:

Failed to get available products: could not get token from authenticator: could not decode token, invalid base64

**Comment by brutesque** [comment]
i've had the same issue, and i believe it was due to a slash or backslash in the private key. after a couple of regenerations, i got a private key without the slash/backslash that allowed me to succesfully authenticate.

**Comment by angelosleebos** [comment]
@brutesque  Thanks for the tip. I refused to believe that the problem was with my private key. I also generated a new key, but it still had backslashes in it, despite the presence of those backslashes, authentication worked.

**Comment by brutesque** [comment]
Might be some other character then. I actually tested a key that didn't work with this plugin, and used it on a python wrapper for the api. That confirmed that the issue wasn't with the key itself, but with this plugin. I couldn't pintpoint exactly what the issue was.

Glad you got it to work.

**Comment by aequitas** [comment]
What version of the provider are you using?

You should not base64 encode the key yourself. It should start with `-----BEGIN PRIVATE KEY-----` and end with `-----END PRIVATE KEY-----`. The part in between is base64 encoded.

I have a key with slashes in it and it works as expected. Afaik a base64 encoded string should not contain backslashes. 

Did this key work for you and now doesn't? Or have you never tried it before and it has never worked?

I'm using my key with an environment variable. Could you try that instead of the `file()` method you use in your example. Or maybe try it with a heredoc as shown in the example in the Readme.md?

**Comment by aequitas** [comment]
I just pushed https://github.com/aequitas/terraform-provider-transip/releases/tag/v0.1.8 which contains an update to the gotransip module (not the latest version yet, but from 6.0.2 to 6.2.0). I've been testing with that build but had not released it yet. Maybe that fixes your problem. If not let me know.

**Comment by aequitas** [comment]
Also https://github.com/aequitas/terraform-provider-transip/releases/tag/0.1.9 is now pushed with gotransip at the current latest version.
