### ISSUE TITLE
Respect rate limits on the TransIP API

### ISSUE THREAD

**Issue by EraYaN** [aequitas/terraform-provider-transip#70]
We have quite a large set of DNS records and this results in going over the request limit when we need to apply twice for example.

Would it be possible to respect the headers that are returned from the API to avoid going over de API rate limit?

**Comment by EraYaN** [comment]
Sometime during the plan during the listing of all the stuff and sometimes during the actual apply portion. Given is basically accesses everything twice it really adds up. It might need some global state to throttle requests before the 429 (or a retry when you hit the 429).

**Comment by aequitas** [comment]
I've added the rate limit as retryable error for the domain resource. That's the easiest fix I could do for now. Since the project is already 2 versions behind on the sdk/framework, I don't want to spend too much time refactoring a lot of code before switching to the latest framework version. The latest release includes the change: https://github.com/aequitas/terraform-provider-transip/releases/tag/v0.1.19
